name: basra
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.5.0
  curved_navigation_bar: ^0.3.4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  carousel_pro: ^1.0.0
  flutter_bloc: ^6.1.1
  http: ^0.12.2
  equatable: ^1.2.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
flutter_icons:
   android: "launcher_icon"
   ios: true
   image_path: "assets/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
   - img_p1/Basra_history.png
   - img_p1/Mosque.png
   - img_p1/Entertainment.png
   - img_p1/Education.png
   - img_p1/Hotel.png
   - img_p1/Restaurants.png
   - img_p1/Photo_gallery.png
   - img_p1/Hospital.png
   - img_p1/Exit.png
   - img_p1/مبادرة.png
   - img_p1/الصفحة الرئيسية.png
   - img_p1/حول التطبيق.png
   - img_p1/كورنيش.PNG
   - img_p1/حول المبادرة.png
   - img_p1/Logo.png
   - img_p1/فريق العمل.png
   - img_p1/email.png
   - img_p1/Team_work.jpg
   - img_p1/arrow.png
   - img_p1/مقترحات.png
   - img_p1/اتصل بنا.png
   - img_p1/Proposal.jpg
   - img_p1/الخريطة.jpg
   - img_p1/map.png
   - img_p2/Img1.jpg
   - img_p2/Img2.jpg
   - img_p2/Img3.jpg
   - img_p2/Img4.jpg
   - img_p2/Img5.png
   - img_p3/img1.jpg
   - img_p3/img2.jpg
   - img_p3/img3.jpg
   - img_p3/img4.jpg
   - img_p3/img5.jpg
   - img_p3/img6.jpg
   - img_p3/img7.jpg
   - img_p4/img1.jpg
   - img_p4/img2.jpg
   - img_p4/img3.jpg
   - img_p4/img4.jpg
   - img_p4/img5.jpg
   - img_p4/img6.jpg
   - img_p4/img7.jpg
   - img_p4/img8.jpg
   - img_p4/img9.jpg
   - img_p4/img10.jpg
   - img_p4/img11.jpg
   - img_p4/img12.jpg
   - img_p5/img1.jpg
   - img_p5/img2.jpg
   - img_p5/img3.jpg
   - img_p5/img4.jpg
   - img_p5/img5.jpg
   - img_p5/img6.jpg
   - img_p6/img1.jpg
   - img_p6/img2.jpg
   - img_p6/img3.jpg
   - img_p6/img4.jpg
   - img_p6/img5.jpg
   - img_p6/img6.jpg
   - img_p6/img7.jpg
   - img_p6/img8.jpg
   - img_p6/img9.jpg
   - img_p6/img10.jpg
   - img_p6/img11.jpg
   - img_p7/img1.jpg
   - img_p7/img2.jpg
   - img_p7/img3.jpg
   - img_p7/img4.jpg
   - img_p7/img5.jpg
   - img_p7/img6.jpg
   - img_p7/img7.jpg
   - img_p7/img8.jpg
   - img_p7/img9.jpg
   - img_p7/img10.jpg
   - img_p7/img11.jpg
   - img_p7/img12.jpg
   - img_p7/img13.jpg
   - img_p7/img14.jpg
   - img_p7/img15.jpg
   - img_p7/img16.jpg
   - img_p7/img17.jpg
   - img_p7/img18.jpg
   - img_p8/img1.PNG
   - img_p8/img2.jpg
   - img_p8/img3.jpg
   - img_p8/img4.jpg
   - img_p8/img5.jpg
   - img_p8/img6.jpg
   - img_p8/img7.jpg
   - img_p8/img8.jpg
   - img_p8/img9.jpg
   - img_p8/img10.jpg








  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
